import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/web/Footer";
import Header from "@/components/web/Header";

// Import all weights: 100–900
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Biolume",
  description: "Generated by create next app",
  icons: {
    icon: "/asset/logo.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
         <Header/>
        {children}
         <Footer />
      </body>
    </html>
  );
}
